### ISSUE TITLE
Pending database schema changes

### ISSUE THREAD

**Issue by moschlar** [moschlar/SAUCE#168]
#1.4
- [x] Test visibility #159 
#1.5
- [ ] More usable public/private visible/invisible settings for entities #154, #132, #125
# xxx
- [x] Source code scaffolds #167 
- [ ] Default language for assignment #110 
- [ ] Model enhancements #107
